name: pycryptor
base: core20
version: git
summary: Visualize primes and fibonacci numbers.
description: |
  PyCryptor is a program that can realize plain text encryption/decription
  with the text it's given. Just a few Cipher algorithms are supported yet.
compression: lzo

grade: devel
confinement: devmode

parts:
  pycryptor:
    plugin: python
    source: .
    stage-packages: 
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0

apps:
  pycryptor:
    command: bin/pycryptor
    extensions: [gnome-3-38]
